services:

  db:
    container_name: postgres
    hostname: db
    image: postgres
    volumes:
      - jms_postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - jms_redis:/data
    restart: unless-stopped

volumes:
  jms_postgres:
  jms_redis:

networks:
  open_network:
   driver: bridge